### ISSUE TITLE
Rename `foo()`

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#104]
There is an internal function defined inline named `foo()`:

https://github.com/Merck/simtrial/blob/b4aeaa730465171b295552cb80ad9ad87eb7bdbd/R/wlr.R#L183

This function should be updated:

1. Rename it to use a meaningful function name. See [foo](https://developers.google.com/style/word-list#foo) in Google's developer documentation style guide.
1. Define it outside the export function. This is because currently this is only accessible within the parent function, and it is being redefined again every time the parent function is called, which is suboptimal for performance.

**Comment by fb-elong** [comment]
How about we call it `z_stat`? If it is OK, you can assign it to me :)

**Comment by nanxstats** [comment]
@fb-elong Sounds great! One small detail: how about `wlr_z_stat()`? I think the `wlr_` prefix clearly indicates that the function is related to the weighted logrank test and makes it easier for developers to identify the related functions. This also leaves space for generalization and extension for future testing methods.

**Comment by nanxstats** [comment]
Fixed by #105
