### ISSUE TITLE
Move `wlr_z_stat()` outside

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#106]
We should move the `wlr_z_stat()` function definition outside of the exported function, to make it an internal function that is not dynamically defined every time the exported function is called.

**Comment by jdblischak** [comment]
Completed in PR #114 (https://github.com/Merck/simtrial/commit/04b36d068e4a3b9b6a8a6c739fa9576be2a556fc#diff-7c6e3f5f69d768b0f61e0c44cdd85ad5c7d11a2b24b485f7a998fbea26004013)
