### ISSUE TITLE
Migrate table backend to data.table

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#111]
We will work on rewriting the table backend of simtrial from dplyr/tidyr to data.table to improve simulation performance. Preliminary benchmarks show that a 2x - 10x speedup is possible for a few existing functions driven by different data sizes and table operations involved.

**Comment by jdblischak** [comment]
Intermediate progress update. I've converted `cut_data_by_date()`, `get_cut_date_by_event()`, `counting_process()`, and `sim_fixed_n()` to data.table.

Using simtrial from 341f77f0a598dc6d638bd5c48746952a7db88255, running `sim_fixed_n()` with 100 simulations takes ~22 seconds:

```R
library("simtrial")
library("foreach")
library("future")
plan(sequential)
library("microbenchmark")
microbenchmark(suppressMessages(sim_fixed_n(n_sim = 100)), times = 10)
## Unit: seconds
##                                        expr      min       lq     mean   median       uq      max neval
##  suppressMessages(sim_fixed_n(n_sim = 100)) 20.48683 22.18765 22.42812 22.70253 23.31057 23.51496    10
```

Using simtrial from [5eef141](https://github.com/jdblischak/simtrial/commit/5eef1411cf46d8e9f91459f55da40beeefcedd3f) on my branch ["data.table"](https://github.com/jdblischak/simtrial/commits/data.table), this now takes ~10 seconds:

```R
devtools::load_all(".")
library("foreach")
library("future")
plan(sequential)
library("microbenchmark")
microbenchmark(suppressMessages(sim_fixed_n(n_sim = 100)), times = 10)
## Unit: seconds
##                                        expr      min       lq     mean   median       uq      max neval
##  suppressMessages(sim_fixed_n(n_sim = 100)) 8.311332 8.527891 10.86475 9.451404 12.88969 17.15582    10
```

**Comment by jdblischak** [comment]
I've mostly converted `sim_pw_surv()`. There still remains a single `group_by()`+`summarize()` due to the difficulty in reproducing the internal sorting of `group_by()`. Still made a difference of a few seconds when doing 100 simulations:

```R
microbenchmark(suppressMessages(sim_fixed_n(n_sim = 100)), times = 10)
## Unit: seconds
##                                        expr      min       lq    mean   median       uq      max neval
##  suppressMessages(sim_fixed_n(n_sim = 100)) 7.398563 7.458874 7.57949 7.581341 7.699942 7.762261    10
```

**Comment by jdblischak** [comment]
To try out my code, you can install the package directly from my fork:

```R
remotes::install_github("jdblischak/simtrial@data.table")
library(simtrial)

# to switch back to the latest GitHub version
detach("package:simtrial")
remotes::install_github("Merck/simtrial")
# you may still need to restart your R session (Ctrl+Shift+F10 in RStudio)
library(simtrial)
```

**Comment by nanxstats** [comment]
> I've mostly converted `sim_pw_surv()`. There still remains a single `group_by()`+`summarize()` due to the difficulty in reproducing the internal sorting of `group_by()`. Still made a difference of a few seconds when doing 100 simulations:

Here is my version in case it's useful. I imposed the ordering manually to be 100% concordance with dplyr results.

<details><summary>Expand code block</summary>

```r
simPWSurv_dt <- function(
    n = 100,
    strata = data.frame(Stratum = "All", p = 1),
    block = c(rep("Control", 2), rep("Experimental", 2)),
    enrollRates = data.frame(rate = 9, duration = 1),
    failRates = data.frame(
      Stratum = rep("All", 4),
      period = rep(1:2, 2),
      Treatment = c(rep("Control", 2), rep("Experimental", 2)),
      duration = rep(c(3, 1), 2),
      rate = log(2) / c(9, 9, 9, 18)
    ),
    dropoutRates = data.frame(
      Stratum = rep("All", 2),
      period = rep(1, 2),
      Treatment = c("Control", "Experimental"),
      duration = rep(100, 2),
      rate = rep(.001, 2)
    )) {
  # start data.table by generating strata and enrollment times
  x <- data.table(
    Stratum = sample(
      x = strata$Stratum,
      size = n,
      replace = TRUE,
      prob = strata$p
    ),
    enrollTime = rpwenroll_dt(n, enrollRates = enrollRates)
  )

  setorder(x, Stratum)
  x[, Treatment := fixedBlockRand_dt(n = .N, block = block), by = .(Stratum)]
  setorder(x, enrollTime)

  x[, c("failTime", "dropoutTime") := .(0, 0)]
  unique_stratum <- unique(x$Stratum)
  unique_treatment <- unique(x$Treatment)

  for (sr in unique_stratum) {
    for (tr in unique_treatment) {
      indx <- x$Stratum == sr & x$Treatment == tr
      n_selected <- sum(indx)
      x[
        indx,
        `:=`(
          failTime = rpwexpinvRcpp(
            n = n_selected,
            failRates = failRates[failRates$Stratum == sr & failRates$Treatment == tr, , drop = FALSE]
          ),
          dropoutTime = rpwexpinvRcpp(
            n = n_selected,
            failRates = dropoutRates[dropoutRates$Stratum == sr & dropoutRates$Treatment == tr, , drop = FALSE]
          )
        )
      ]
    }
  }

  # set calendar time-to-event and failure indicator
  x[, c("cte", "fail") := .(
    pmin(dropoutTime, failTime) + enrollTime,
    as.integer(failTime <= dropoutTime) * 1
  )]

  x[]
}
```

</details>

Note that this is based on an earlier version of the function so the names might be a bit different.

**Comment by jdblischak** [comment]
> Here is my version in case it's useful. I imposed the ordering manually to have 100% concordance with dplyr results.

Thanks @nanxstats! Yes, very useful. I was so close. I had experimented with sorting, but I hadn't figured out to sort by different columns before and after the grouping operation. Finished in [f96b8d9](https://github.com/jdblischak/simtrial/commit/f96b8d995c0820c8558cb5ea4ac0fe6cfd336dc2)

**Comment by jdblischak** [comment]
Another progress update:

* I've removed all the dplyr calls in the code path followed by `sim_fixed_n()` (`trace()` prints to the console when a function has been called, so we want no output):

* I've reduced the runtime for 100 simulations from an initial ~22 seconds down to ~4 seconds


```R
devtools::load_all(".")
library("foreach")
library("future")
plan(sequential)
trace(dplyr::select)
trace(dplyr::mutate)
trace(dplyr::group_by)
trace(dplyr::summarize)
trace(dplyr::lag)
x <- sim_fixed_n(n_sim = 2)

library("microbenchmark")
microbenchmark(suppressMessages(sim_fixed_n(n_sim = 100)), times = 10)
## Unit: seconds
##                                        expr      min       lq     mean   median       uq    max neval
##  suppressMessages(sim_fixed_n(n_sim = 100)) 4.022388 4.184973 4.388432 4.359366 4.498875 4.8553    10
```

**Comment by jdblischak** [comment]
In order to compare head-to-head performance, I installed simtrial from commit 341f77f as {simtrialBefore}. Full results below, but a quick summary on the relative performance depending on the number of cores:

| cores | relative speed improvement |
|--------|--------|
| 1 | ~5.5x |
| 4 | ~2.25x |
| 8 | ~2.18x | 


```R
library("simtrialBefore") # commit 341f77f
library("simtrial")       # commit 206ca44

library("foreach")
library("future")
plan(sequential)
library("microbenchmark")

microbenchmark(
  before = simtrialBefore::sim_fixed_n(n_sim = 100),
  after = simtrial::sim_fixed_n(n_sim = 100),
  times = 10,
  unit = "relative"
)
## Unit: relative
##    expr      min       lq     mean   median       uq      max neval
##  before 5.039001 5.340332 5.425266 5.546034 5.281608 5.892134    10
##   after 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    10

plan(multisession, workers = 4)
microbenchmark(
  before = simtrialBefore::sim_fixed_n(n_sim = 100),
  after = simtrial::sim_fixed_n(n_sim = 100),
  times = 10,
  unit = "relative"
)
## Unit: relative
##    expr      min      lq     mean   median       uq      max neval
##  before 2.334337 2.20446 2.152603 2.257186 2.147251 1.644671    10
##   after 1.000000 1.00000 1.000000 1.000000 1.000000 1.000000    10

plan(multisession, workers = 8)
microbenchmark(
  before = simtrialBefore::sim_fixed_n(n_sim = 100),
  after = simtrial::sim_fixed_n(n_sim = 100),
  times = 10,
  unit = "relative"
)
## Unit: relative
##    expr      min       lq     mean   median       uq      max neval
##  before 2.744738 2.098391 1.819507 2.180163 1.692861 1.002374    10
##   after 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    10
```

**Comment by nanxstats** [comment]
I appreciate the benchmark. A few initial thoughts:

- I'm very satisfied to see the ~5.5x single core performance boost. That's the difference between finishing a simulation within a week before the data.table rewrite vs. within a day after the rewrite. Mission accomplished!

- Increasing `n_sim` to a much larger number might give results closer to theoretical estimates ([Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law)) as the parallel overhead for a small number of simulations can be large.

- I also wonder if it would yield better results using identical core designs like AMD CPUs instead of the P cores + E cores designs in latest Intel and Apple Silicon CPUs because the E cores might become the bottleneck... In any case, I will also try this out with my Ryzen 7950X3D setup (16 cores 32 threads all identical cores).

**Comment by jdblischak** [comment]
Updated results for 8 cores and 1000 simulations. The median speed improvement increased to ~2.58x (from ~2.18x with 100 simulations)

```R
library("simtrialBefore") # commit 341f77f
library("simtrial")       # commit 206ca44

library("foreach")
library("future")
library("microbenchmark")

plan(multisession, workers = 8)
microbenchmark(
  before = simtrialBefore::sim_fixed_n(n_sim = 1000),
  after = simtrial::sim_fixed_n(n_sim = 1000),
  times = 10,
  unit = "relative"
)
## Unit: relative
##    expr      min       lq     mean   median       uq      max neval
##  before 5.158855 3.750657 3.554954 2.580933 2.616116 5.073521    10
##   after 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    10
```

**Comment by nanxstats** [comment]
I also did some benchmarking, see [this gist](https://gist.github.com/nanxstats/cf71094cc730147a0fc230b86f642db3) for code and results. (7950X3D + 64G RAM)

I used a slightly larger `n_sim = 960` and different benchmarking tools (tictoc + 10x for-loop). I saw a ~4x boost on single core performance which is impressive and generally aligns with your results. The parallel speedup with <= 4 cores on both sides also makes sense.

My interpretation for the situation on >= 8 cores is that the data.table implementation is so fast - it easily reaches the point of parallel overhead is not ignorable anymore after 4 cores... To see a more monotonic curve, we basically need larger `n_sim` and maybe increase the per-simulation difficulty.

<details>
<summary>Expand plots</summary>

![df_time](https://github.com/Merck/simtrial/assets/199363/248d339a-525e-4770-afe8-830ca630ccb3)

![df_speedup](https://github.com/Merck/simtrial/assets/199363/c693f4e3-e650-4b26-be0f-19029f1085bc)

</details>

**Comment by nanxstats** [comment]
I updated [the gist](https://gist.github.com/nanxstats/cf71094cc730147a0fc230b86f642db3) to increase `n_sim` to 10k and use only up to 16 cores this time. Now the speed up becomes linear for dplyr all the way to 16 cores, and linear for data.table until 8 cores. Same guess: data.table implementation is fast so it's easier to get to the point where parallel overhead is not ignorable.

With this result, I'm relatively confident that (for academic purposes) we can make the speed up vs. cores curves linear for both backends by simply increasing `n_sim` further.

<details>
<summary>Expand plots (n_sim = 10k)</summary>

![time](https://github.com/Merck/simtrial/assets/199363/167ca8aa-b5af-40af-8c4b-c57b7239ff77)

![speedup](https://github.com/Merck/simtrial/assets/199363/574990b1-6e05-48e6-8c63-73d352baad7d)

</details>

**Comment by jdblischak** [comment]
I think this can be closed now. I have converted all the existing and recently added functions to use data.table internally. All the functions continue to accept data frames, tibbles, or data tables as input, and always return data frames. I moved dplyr and tidyr to Suggests (so they can still be used in tests and examples) and removed tibble.

**Comment by nanxstats** [comment]
I agree. Thanks so much for the rewrite! I think it's quite an achievement.

**Comment by nanxstats** [comment]
The updated code that plot with log-transformed y-axis is available from the simtrial CRAN release [blog post source code](https://github.com/keaven/keaven.github.io/blob/main/content/blog/2023-12-11-simtrial/images/table-backend-plot.R.txt).
