### ISSUE TITLE
Vignette for `get_analysis_date()`

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#140]
Need a vignette for `get_analysis_date()`.

**Comment by LittleBeannie** [comment]
Is the help page with 7 examples sufficient?

**Comment by LittleBeannie** [comment]
As discussed with Keaven yesterday, our initial focus will be on enhancing the help file. Once that is accomplished, we can explore the possibility of creating a vignette to present additional stories in a narrative format.
