### ISSUE TITLE
Add FAQ vignette

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#180]
To me, many important questions asked about simtrial so far can be summarized and compiled into a "frequently asked questions" vignette, so that we can save some time to avoid answering them repeatedly.

As an example, data.table has a rather detailed [FAQ vignette](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.html).

**Comment by LittleBeannie** [comment]
Decision: not doing for now, can be a future issue
