### ISSUE TITLE
Remove modestWLRT as a remote dependency

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#20]
The title says it: CRAN cannot accept packages with GitHub dependencies.

You should either

- ask the modestWLRT authors to make their packages available on CRAN, or
- port the code over as part of simtrial

**Comment by LittleBeannie** [comment]
Removed

**Comment by nanxstats** [comment]
I still see modestWLRT in the current version of [DESCRIPTION](https://github.com/Merck/simtrial/blob/447896eb5b44fe7c4ee0ecd7c1b4b0e39581690d/DESCRIPTION#L61) so I'm reopening this.
