### ISSUE TITLE
Remove the `seed` argument from `sim_gs_n()`

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#202]
In principle, functions should respect the seed from the environment. User are expected to set the seed outside of the function call, not inside the function call.

There is an argument `seed` in `sim_gs_n()`. @jdblischak could you help removing this argument and update the examples/tests so they set the seed using the canonical `set.seed()` approach?

Historical context: `sim_fixed_n()` was initially implemented with a similar `seed` argument, which was not ideal. This situation was fixed by @cmansch when refactoring the parallelization adaptor in #110.

**Comment by cmansch** [comment]
I believe this was closed in the `sim_gs_n()` parallelization PR (xref: https://github.com/Merck/simtrial/pull/249)

**Comment by nanxstats** [comment]
Great! I appreciate the efforts to make this canonical, closing this now.
