### ISSUE TITLE
Formula parsing: match by argument names instead of by position

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#220]
This is a follow up on https://github.com/Merck/simtrial/pull/216 about the new formula interface for `rmst()`.

I agree that we should not evaluate the `Surv()` call and only extract the variable names from the formula. I do think that having a single, canonical syntax would be beneficial, such as `Surv(month, status) ~ trt)`, and safeguard common pitfalls with essential enforcement so it's difficult for users to write the wrong code without realizing.

Aligned with this spirit, @jdblischak's [comment](https://github.com/Merck/simtrial/pull/216#issuecomment-2000076501) is right on point that matching by position when parsing the formula is dangerous as people could write legal `Surv()` calls with shuffled argument positions such as `Surv(event = status, time = month) ~ trt` without realizing the matched variables will be wrong.

So, here is an _ad hoc_ "solution" to the problem. I wonder if either rlang or [adv-r first edition](http://adv-r.had.co.nz/Expressions.html) has better, direct alternatives.

``` r
# Copied from <https://github.com/cran/stackoverflow/blob/master/R/match.call.default.R>
match_call_defaults <- function(
    definition = sys.function(sys.parent()),
    call = sys.call(sys.parent()),
    expand.dots = TRUE,
    envir = parent.frame(2L)) {
  call <- match.call(definition, call, expand.dots, envir)
  formals <- formals(definition)

  if (expand.dots && "..." %in% names(formals)) formals[["..."]] <- NULL
  for (i in setdiff(names(formals), names(call))) call[i] <- list(formals[[i]])

  match.call(definition, call, TRUE, envir)
}

rmst <- function(data, formula = NULL) {
  formula <- as.formula(formula)
  var_label_group <- attr(stats::terms(formula), "term.labels")[1]
  surv_call <- attr(stats::terms(formula), "variables")[[2]]
  surv_call_match <- match_call_defaults(definition = function(time, event) {}, surv_call)
  var_label_tte <- as.character(surv_call_match$time)
  var_label_event <- as.character(surv_call_match$event)

  c(
    "var_label_tte" = var_label_tte,
    "var_label_event" = var_label_event,
    "var_label_group" = var_label_group
  )
}

# rhs - will always and only match the very first term
rmst(formula = Surv(month, status) ~ trt + trt2)
#>   var_label_tte var_label_event var_label_group
#>         "month"        "status"           "trt"

# lhs - canonical case works
rmst(formula = Surv(month, status) ~ trt)
#>   var_label_tte var_label_event var_label_group
#>         "month"        "status"           "trt"

# lhs - all named arguments work
rmst(formula = Surv(event = status, time = month) ~ trt)
#>   var_label_tte var_label_event var_label_group
#>         "month"        "status"           "trt"

# lhs - abbreviate first argument name works
rmst(formula = Surv(month, event = status) ~ trt)
#>   var_label_tte var_label_event var_label_group
#>         "month"        "status"           "trt"

# lhs - partial positional matching - not common but works
rmst(formula = Surv(event = status, month) ~ trt)
#>   var_label_tte var_label_event var_label_group
#>         "month"        "status"           "trt"

# lhs - giving more or fewer arguments will not work - can use some handling
rmst(formula = Surv(month) ~ trt)
#>   var_label_tte var_label_group
#>         "month"           "trt"
rmst(formula = Surv(month, month2, status) ~ trt)
#> Error in match.call(definition, call, expand.dots, envir): unused argument (status)
```

**Comment by jdblischak** [comment]
> I do think that having a single, canonical syntax would be beneficial, such as `Surv(month, status) ~ trt)`, and safeguard common pitfalls with essential enforcement so it's difficult for users to write the wrong code without realizing.

I'm open to making the formula parsing more sophisticated if we can decide on a single canonical syntax

> So, here is an _ad hoc_ "solution" to the problem. I wonder if either rlang or [adv-r first edition](http://adv-r.had.co.nz/Expressions.html) has better, direct alternatives.

I don't see anything obvious in the section [Capturing the current call](http://adv-r.had.co.nz/Expressions.html#capturing-call) that would improve this

Though could you provide an example of why `match_call_defaults()` is required? When I replace it with a simple call to `match.call()`, all your examples return the same results

```R
rmst <- function(data, formula = NULL) {
  formula <- as.formula(formula)
  var_label_group <- attr(stats::terms(formula), "term.labels")[1]
  surv_call <- attr(stats::terms(formula), "variables")[[2]]
  surv_call_match <- match.call(definition = function(time, event) {}, surv_call)
  var_label_tte <- as.character(surv_call_match$time)
  var_label_event <- as.character(surv_call_match$event)
  
  c(
    "var_label_tte" = var_label_tte,
    "var_label_event" = var_label_event,
    "var_label_group" = var_label_group
  )
}

# rhs - will always and only match the very first term
rmst(formula = Surv(month, status) ~ trt + trt2)
## var_label_tte var_label_event var_label_group 
## "month"        "status"           "trt" 

# lhs - canonical case works
rmst(formula = Surv(month, status) ~ trt)
## var_label_tte var_label_event var_label_group 
## "month"        "status"           "trt" 

# lhs - all named arguments work
rmst(formula = Surv(event = status, time = month) ~ trt)
## var_label_tte var_label_event var_label_group 
## "month"        "status"           "trt" 

# lhs - abbreviate first argument name works
rmst(formula = Surv(month, event = status) ~ trt)
## var_label_tte var_label_event var_label_group 
## "month"        "status"           "trt" 

# lhs - partial positional matching - not common but works
rmst(formula = Surv(event = status, month) ~ trt)
## var_label_tte var_label_event var_label_group 
## "month"        "status"           "trt" 

# lhs - giving more or fewer arguments will not work - can use some handling
rmst(formula = Surv(month) ~ trt)
## var_label_tte var_label_group 
## "month"           "trt" 

rmst(formula = Surv(month, month2, status) ~ trt)
## Error in match.call(definition, call, expand.dots, envir) : 
##   unused argument (status)
```

**Comment by nanxstats** [comment]
Well, I would suggest the single canonical syntax be `Surv(month, status) ~ trt)`, but I could be biased, so would love to hear the group's feedback.

If `match.call()` can already do it, that would be perfect. No need for complexity at all.

**Comment by jdblischak** [comment]
@LittleBeannie could you please add this to the discussion list for our next group meeting? In regards to the argument `formula` of `rmst()`, we need to decide:

1. Should we require a single canonical syntax for the formula, and immediately error for a formula with any deviations?
2. If yes to the above, what should the single canonical syntax be?

For context, from a technical perspective, this change should be straightforward for me to implement once the group decides on the above.
