### ISSUE TITLE
`maxcombo`: shall we report the index of the test we use for the p-value calculation?

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/simtrial#224]
In a maxcombo test for a single test, there are multiple tests which gives couple of Z. For example

- Regular logrank test --> Z1
- Weighted logrank test with FH(0, 0.5)  --> Z2
- Weighted logrank test with FH(0.5, 0.5)  --> Z3

Considering there are 3 Z statistics, which Z is used for the p-value calculation. Shall we report the index of the Z used?

Reference: https://github.com/Merck/simtrial/blob/main/R/pvalue_maxcombo.R#L73

**Comment by nanxstats** [comment]
If there is value in knowing this down the line and you want to be developer-friendly, then including the information about the test along with the simple numeric result would be advisable.

**Comment by LittleBeannie** [comment]
Decision: the following will be part of maxcombo test
- p-value, 
- index of max(Z), 
- whatever i put maxcombo, also report the Z value of WLR-FH(0,0) WLR-FH(0, 0.5)
