### ISSUE TITLE
Replace `rlang::is_installed()` with a lightweight solution

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#246]
I used `rlang::is_installed()` and introduced rlang as a hard dependency in #245 to safeguard code examples, tests, and vignettes and get the package pass the `noSuggests` check.

It would be ideal if we can use a lightweight solution here and remove the dependency.

@jdblischak suggested `requireNamespace()`. @yihui also mentioned `xfun::loadable()`.

**Comment by jdblischak** [comment]
I propose the following internal function:

```R
is_installed <- function(package) requireNamespace(package, quietly = TRUE)
```

The only difference is that it returns its value invisibly

**Comment by nanxstats** [comment]
Sounds good. `xfun::loadable()` does a bit more by using `suppressPackageStartupMessages(requireNamespace(pkg, quietly = TRUE))` and I wonder if `suppressPackageStartupMessages()` handles some particular edge cases.

**Comment by yihui** [comment]
> I propose the following internal function:
> 
> ```r
> is_installed <- function(package) requireNamespace(package, quietly = TRUE)
> ```
> 
> The only difference is that it returns its value invisibly

I think that's good enough. No need to consider package startup messages, since this function is currently used only for `R CMD check` purpose.
