### ISSUE TITLE
Update internal variables to make it in snake case

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/simtrial#27]
For example, in [fixedBlockRand.R](https://github.com/Merck/simtrial/blob/main/R/fixedBlockRand.R), there are some internal variables doesn't follow the snake case, like `nblock` and `ntot`.

**Comment by nanxstats** [comment]
The file names are also not canonical.

I recommend using lower case words connected with hyphens (`-`), i.e., `fixed-block-rand.R`.
