### ISSUE TITLE
`as_gt()`: a function name shared in both gsDesign2 and simtrial

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/simtrial#284]
In both gsDesign2 and simtrial, there are functions named `as_gt()`. If users load both packages, it might cause confusion regarding which `as_gt()` is being called.

Is there a user-friendly way to call `as_gt()` without typing `gsDesign2::`?

![image](https://github.com/user-attachments/assets/6944695c-71d6-4dd0-8503-e2630de9c739)

**Comment by LittleBeannie** [comment]
Decision: we will start with John's idea, if not workable, then we will try Yihui's print method. 
Timeline: before the next CRAN release (2024/10/31)

**Comment by nanxstats** [comment]
I do have some concerns on extending `print()`: `print()` often implies the (main) default behavior being the printing side effect + the **inputs** invisibly returned, while `as_gt()` is different. As the name suggests, it returns the gt object visibly. There is a good reason why this name was chosen, and that's because it's the most fitting, intuitive name.

**Comment by jdblischak** [comment]
My proposed solution of making the `as_gt()` generics from gsDesign2 and simtrial aware of each other is in https://github.com/Merck/simtrial/pull/287. If we like this approach, then we'd need a similar PR to gsDesign2

**Comment by jdblischak** [comment]
The option of making a 3rd package that defines the generic `as_gt()` is the same strategy as the package [r-lib/generics](https://github.com/r-lib/generics). For example, it defines the generic function `tidy()`, so even though both {broom} and {recipe} define S3 methods for `tidy` (and even re-export it via `export(tidy)`), the package load order does not matter.

```R
library("broom")
library("recipes")
## 
## Loading required package: dplyr
## 
## Attaching package: ‘dplyr’
## 
## The following objects are masked from ‘package:stats’:
##   
##   filter, lag
## 
## The following objects are masked from ‘package:base’:
##   
##   intersect, setdiff, setequal, union
## 
## 
## Attaching package: ‘recipes’
## 
## The following object is masked from ‘package:stats’:
##   
##   step
## 

tidy
## function (x, ...) 
## {
##   UseMethod("tidy")
## }
## <bytecode: 0x0000021722772650>
## <environment: namespace:generics>
```
