### ISSUE TITLE
Should calculation of `sim_upper_prob` use `cumsum()`?

### ISSUE THREAD

**Issue by jdblischak** [Merck/simtrial#288]
I am confused by the column `sim_upper_prob` calculated by `summary.simtrial_gs_wlr()` (added in #268)

https://github.com/Merck/simtrial/blob/58db5df1bad0240493661a3cdd30326b6d064910/R/summary.R#L111-L113

I assumed it would be "the number of times the upper bound was crossed" (`n_cross_upper`) divided by "the number of simulations" (`n_sim`). However, that isn't the case because of the use of `cumsum()`. Below is a demonstration based on the example in `?summary`:

```R
n_sim <- 3
d <- tibble::tibble(
  sim_id = 1:3,
  analysis = c(3, 2, 3),
  upper_bound = c(1.9930475226539421, 2.511427013856541, 1.9930475226539421),
  cross_upper = rep(TRUE, 3L),
)
d |>
  dplyr::group_by(analysis) |>
  dplyr::summarize(n_cross_upper = dplyr::n()) |>
  dplyr::mutate(
    cumulative = cumsum(n_cross_upper),
    sim_upper_prob = cumsum(n_cross_upper) / n_sim,
    sim_upper_prob_nocumsum = n_cross_upper / n_sim
  )
## # A tibble: 2 × 5
##   analysis n_cross_upper cumulative sim_upper_prob sim_upper_prob_nocumsum
##      <dbl>         <int>      <int>          <dbl>                   <dbl>
## 1        2             1          1          0.333                   0.333
## 2        3             2          3          1                       0.667
```

The upper bound was crossed 1 time for analysis 2 and 2 times for analysis 3. Thus I think `sim_upper_prob` should be 1/3 and 2/3. However, because `cumsum()` adds `1 + 2`, currently the `sim_upper_prob` would be assigned value of 1.

**Comment by jdblischak** [comment]
I suspect I am wrong about the calculation of `sim_upper_prob`. I did some experiments, and `sim_upper_prob` never goes above 1, even when I artificially added many more cuts. If this was a mistake, then by chance there should occasionally be more boundary crossings than the number of simulations (especially with 6 cuts and only 3 simulations).

@LittleBeannie I apologize if this is painfully obvious to a domain expert, but perhaps we could document somewhere how the total number of boundary crossing events are constrained to fewer than `n_sim` even across many analyses/cuts.

**Comment by LittleBeannie** [comment]
Hi @jdblischak, thanks for sharing your confusion. The key lies in the `group_by(analysis)`. With a group by analysis, the `n_cross_upper` is the number of simulations cross upper bound AT a certain analysis. Afterwards, the `cumsum()` cumulatively sum the number of simulations cross upper bound BY a certain analysis.  

Hope the above explanations works for you!

**Comment by jdblischak** [comment]
> The key lies in the `group_by(analysis)`. With a group by analysis, the `n_cross_upper` is the number of simulations cross upper bound AT a certain analysis. Afterwards, the `cumsum()` cumulatively sum the number of simulations cross upper bound BY a certain analysis.

My confusion is what is constraining the number of simulations that cross the upper bound. If there are X simulations at each of Y analyses, my naive expectation was that the maximum number of simulations that potentially cross the upper bound is X * Y. That clearly does not appear to be the case in practice. Something is constraining the total number of boundary crossing events to be <=X. In other words, if there are X boundary crossing in the first analysis, then none of the simulations in the subsequent analyses will cross the boundary. From my perspective just reading the code, there is nothing coupling the analyses between each run of the `for` loop. However, there must be something inherent in the statistical properties of each analysis that maintains this constraint.

If this statistical relationship across the analyses is obvious to a domain expert like yourself, then there is no need to document it further.
