### ISSUE TITLE
Fix CRAN pre-tests 

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/simtrial#296]
```
* using log directory 'd:/RCompile/CRANincoming/R-devel/simtrial.Rcheck'
* using R Under development (unstable) (2024-10-30 r87277 ucrt)
* using platform: x86_64-w64-mingw32
* R was compiled by
    gcc.exe (GCC) 13.2.0
    GNU Fortran (GCC) 13.2.0
* running under: Windows Server 2022 x64 (build 20348)
* using session charset: UTF-8
* checking for file 'simtrial/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'simtrial' version '0.4.2'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... [14s] NOTE
Maintainer: 'Yujie Zhao <yujie.zhao@merck.com>'

Unknown, possibly misspelled, fields in DESCRIPTION:
  'Remotes'
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'simtrial' can be installed ... OK
* used C++ compiler: 'g++.exe (GCC) 13.2.0'
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... NOTE
Problems with news in 'NEWS.md':
  Cannot extract version info from the following section titles:
    Coding Improvements
* checking code files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... [15s] OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking LazyData ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compilation flags used ... OK
* checking compiled code ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ... [26s] OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ... [108s] OK
  Running 'testthat.R' [108s]
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... OK
* checking re-building of vignette outputs ... [58s] OK
* checking PDF version of manual ... [22s] OK
* checking HTML version of manual ... OK
* DONE
Status: 2 NOTEs
```

**Comment by jdblischak** [comment]
> do you happen to know the reason for causing `Cannot extract version info from the following section titles: Coding Improvements`?

I thought we fixed that NOTE with https://github.com/Merck/simtrial/pull/294/commits/3af037115a445c2c67a4820df943112e7f3974da (explanation in https://github.com/Merck/simtrial/pull/294#discussion_r1823320866). Could you please check your local `NEWS.md` file and confirm it has `## Coding Improvements`?

**Comment by jdblischak** [comment]
```
Unknown, possibly misspelled, fields in DESCRIPTION:
  'Remotes'
```

We can't use `Remotes` for a CRAN submission

https://github.com/Merck/simtrial/blob/ce4f1a26005509195a841bcec7b32eaa3dfee77a/DESCRIPTION#L66

If {simtrial} truly requires the latest version of {gsDesign2}, then we'll need to submit {gsDesign2} to CRAN first. Once it has been accepted, then we can remove the `Remotes` field for {simtrial} (and also add the `>=` requirement for {gsDesign2} in `Imports`)

**Comment by jdblischak** [comment]
Also, as you make the final preparations for CRAN, don't forget about the minor documentation updates in PR https://github.com/Merck/simtrial/pull/295

**Comment by LittleBeannie** [comment]
> ```
> Unknown, possibly misspelled, fields in DESCRIPTION:
>   'Remotes'
> ```
> 
> We can't use `Remotes` for a CRAN submission
> 
> https://github.com/Merck/simtrial/blob/ce4f1a26005509195a841bcec7b32eaa3dfee77a/DESCRIPTION#L66
> 
> If {simtrial} truly requires the latest version of {gsDesign2}, then we'll need to submit {gsDesign2} to CRAN first. Once it has been accepted, then we can remove the `Remotes` field for {simtrial} (and also add the `>=` requirement for {gsDesign2} in `Imports`)

The remotes has been removed.

**Comment by jdblischak** [comment]
> The remotes has been removed.

I don't follow. Are you saying that you removed it locally and are going to send a PR? Because it definitely exists for the tag v0.4.2: https://github.com/Merck/simtrial/blob/v0.4.2/DESCRIPTION#L66

**Comment by LittleBeannie** [comment]
> > The remotes has been removed.
> 
> I don't follow. Are you saying that you removed it locally and are going to send a PR? Because it definitely exists for the tag v0.4.2: https://github.com/Merck/simtrial/blob/v0.4.2/DESCRIPTION#L66

I am preparing v0.4.3 for CRAN resubmission with remotes deleted, since simtrial does not always require the latest gsDesign2 in GitHub master.
