### ISSUE TITLE
Refactor parallelization code using `%dofuture%`

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#77]
For simtrial's parallelization implementation, I think the goals should be:

- Use L'Ecuyer-CMRG random seed generation
- Reproducible results
- Parallel backend-independent
- Allow additional levels of nested parallel loops in user code
- Hide the low-level details from users

The tidymodels team handles the L'Ecuyer-CMRG seed generation internally (see `generate_seed()`, tidymodels/tune issue 377, and their [vignette](https://tune.tidymodels.org/articles/extras/optimizations.html#parallel-processing)) - and it works for the mainstream backends including doParallel, doRNG, and doFuture. Understanding their approach first could help us build a robust parallelization solution here.

**Comment by nanxstats** [comment]
All of these can be implemented simply via the latest `%dofuture%` approach: https://www.jottr.org/2023/06/26/dofuture/

**Comment by LittleBeannie** [comment]
Timeline: after issue #23 and end of 2023

**Comment by nanxstats** [comment]
Our colleague @cmansch might also be able to help this design and refactor.

**Comment by nanxstats** [comment]
I'm happy to report that @cmansch has made substantial progress on refactoring this using the modern `%dofuture%` approach - we will be expecting a pull request. 😃
