### ISSUE TITLE
Isolate implementation from interface for tabular inputs

### ISSUE THREAD

**Issue by nanxstats** [Merck/simtrial#97]
Currently, we define tabular inputs as such in some functions:

```r
function(n = NULL, enroll_rate = tibble(duration = c(1, 2), rate = c(2, 5))
```

For tabular inputs like `enroll_rate`, it would be ideal to isolate the detailed implementation (creating a table with tibble or other table backend) from the interface, by providing a wrapper to generate the specific input, without the user calling `tibble::tibble()` explicitly.

Such isolation would help us:

1. Rewrite easily with other possible table backends for the table operations, without having to check what the input type is and conduct possible conversions.
2. Make input checking and assertions happen right at the time they are constructed.

**Comment by nanxstats** [comment]
I will send a PR to address this issue.

**Comment by nanxstats** [comment]
My proposal is to have five exported functions to create the input data frames: `enroll_rate()`, `fail_rate()`, `dropout_rate()`, `stratum()`, `rho_gamma()`.

The tabular input definitions (column order, existence, naming) are not 100% consistent in simtrial at the moment - which might need to be revised to make them consistent. Otherwise, we will need to create a separate function for each function that has a divergent definition of the same or similar input concept.

Here is how they are currently defined.

## `enroll_rate`

`sim_pw_surv()`

```r
enroll_rate = tibble(rate = 9, duration = 1)
```

`sim_fixed_n()`

```r
enroll_rate = tibble(duration = c(2, 2, 10), rate = c(3, 6, 9))
```

`rpw_enroll()`

```r
enroll_rate = tibble(duration = c(1, 2), rate = c(2, 5))
```

## `dropout_rate`

`sim_pw_surv()`

```r
dropout_rate = tibble(
  stratum = rep("All", 2),
  period = rep(1, 2),
  treatment = c("control", "experimental"),
  duration = rep(100, 2),
  rate = rep(.001, 2)
)
```

## `fail_rate`

`sim_pw_surv()`

```r
fail_rate = tibble(
  stratum = rep(c("Positive", "Negative"), 2),
  period = rep(1, 4),
  treatment = c(rep("control", 2), rep("experimental", 2)),
  duration = rep(1, 4),
  rate = log(2) / c(6, 9, 9, 12)
)
```

`sim_fixed_n()`

```r
fail_rate = tibble(
  stratum = "All",
  duration = c(3, 100),
  fail_rate = log(2) / c(9, 18),
  hr = c(.9, .6),
  dropout_rate = rep(.001, 2)
)
```

`rpwexp()`

```r
fail_rate = tibble(
  rate = 5,
  duration = 1
)
```

`simfix2simpwsurv()` - same as `sim_fixed_n()`.

## `stratum`

`sim_pw_surv()`

```r
stratum = tibble(
  stratum = c("Positive", "Negative"),
  p = c(.5, .5)
)
```

`sim_fixed_n()`

```r
stratum = tibble(stratum = "All", p = 1)
```

## `rho_gamma`

`wlr()`

```r
rho_gamma = tibble(
  rho = c(0, 0, 1, 1),
  gamma = c(0, 1, 0, 1)
)
```

**Comment by LittleBeannie** [comment]
Timeline: before the end of 2023

**Comment by nanxstats** [comment]
I'm closing this to continue the high-level discussion in #185.
